### PR TITLE
Update chapter4.txt

### PR DESCRIPTION
**Pull request by Hemant112-hub**
add some extra games in you chapter 4

### CODE REVIEW

**Comment by Hemant112-hub** [comment]
in previous you only write one game i added some games that i like to play in my childhood i love that games so much

**Review by Hemant112-hub — COMMENTED** [review]
good job

**Comment by Hemant112-hub** [comment]
good job

**Comment by Hemant112-hub** [comment]
good

**Review by Himanshu-cyber-alt — APPROVED** [review]
good job hemant i like that

**Pull request merged**
